#!/bin/sh
# Xsetup - run as root before the login dialog appears

GEOMETRY_X_SET=$(xprop -notype -len 16 -root _NET_DESKTOP_GEOMETRY | awk '{print $3}' | sed 's/.$//')
GEOMETRY_Y_SET=$(xprop -notype -len 16 -root _NET_DESKTOP_GEOMETRY | awk '{print $4}')

TOUCHSCREEN_X_SET=$(awk "BEGIN {print 1280 / ( 1280 + $GEOMETRY_X_SET )}")
TOUCHSCREEN_Y_SET=$(awk "BEGIN {print 800 / ( 800 + $GEOMETRY_Y_SET )}")

EXTERNAL_SCREEN_STATUS=$(xrandr | grep 'DisplayPort' | awk '{print $2}')
TOUCHSCREEN_ID=$(xinput | grep 'FTS3528' | head -n 1 | awk '{print $5}' | sed 's/id=//g')
CURRENT_DISPLAY_SERVER=$(xrandr | grep -w 'connected' | awk '{print $1}')

if [ "$EXTERNAL_SCREEN_STATUS" = "connected" ]; then
    xrandr  --fb 3200x1080 \
            --output "$CURRENT_DISPLAY_SERVER" --mode 800x1280 --rotate right \
            --output DisplayPort-0 --mode "$GEOMETRY_X_SET"x"$GEOMETRY_Y_SET" --right-of eDP
    xinput set-prop "$TOUCHSCREEN_ID" 'Coordinate Transformation Matrix' 0 "$TOUCHSCREEN_X_SET" 0 -"$TOUCHSCREEN_Y_SET" 0 "$TOUCHSCREEN_Y_SET" 0 0 1
else
    xrandr --output "$CURRENT_DISPLAY_SERVER" --mode 800x1280 --rotate right
    xinput set-prop "$TOUCHSCREEN_ID" 'Coordinate Transformation Matrix' 0 1 0 -1 0 1 0 0 1
fi
